import { expect, test } from "bun:test";
import { parseInput, part1, part2 } from "./07";

const rawInput = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
`;

let input = parseInput(rawInput);

test("part1", () => {
  expect(part1(input)).toBe(21);
});

test("part2", () => {
  expect(part2(input)).toBe(40);
});
